### ISSUE TITLE
Issue on w3 library

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/trader#179] opened 2023-12-12 21:57 UTC
The following issue appeared randomly:

```
[2023-12-12 11:32:49,922][ERROR] [agent] Could not calculate the buy amount: Message(sender=valory/ledger:0.19.0,to=valory/trader_abci:0.1.0,code=500,data=b'',dialogue_reference=('9d500c7f38751379844485090a6cf577566dd96f570dc686e80f6012f0a15fd1', '5bd5e40ae2c36776ff324220b3e13b256dcf85d7ada00c75b5bb773e62dd55a3'),message=Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/web3/_utils/contract_error_handling.py", line 76, in _parse_error_with_reverted_prefix
    error = bytes.fromhex(error).decode("utf8")
            ^^^^^^^^^^^^^^^^^^^^

ValueError: non-hexadecimal number found in fromhex() arg at position 0
,message_id=-1,performative=error,target=1)
```

**Comment by Adamantios** [comment] 2024-01-03 09:24
Closing this issue for the following reasons:

1. Could not recreate it wit the provided information.
2. This is not a fatal error, this is just a log informing that there was an error during the execution of the contract method [calc_buy_amount](https://github.com/valory-xyz/trader/blob/a718875a94e8c69e3984320e1c7fba9e7895e426/packages/valory/contracts/market_maker/contract.py#L85C1-L109). 
3. This was most probably caused by a temporary RPC issue and does not relate to the code and also does not prevent the service from making progress.

**Closed by Adamantios** 2024-01-03 09:24 UTC
Labels: bug
